### ISSUE TITLE
Le CHANGELOG n'apparaît pas

### ISSUE THREAD

**Issue by maelvls** [touist/touist.github.io#2]
Coucou @Erim32,
Lorsque je clique sur "CHANGELOG", rien n'apparait. Lorsque je reagrde la console, je vois ça : 
![capture d ecran 2016-11-25 a 12 43 38](https://cloud.githubusercontent.com/assets/2195781/20624411/118c7bac-b30d-11e6-8c62-06f0884f8d08.png)
As-tu des idées ? :)

**Comment by Erim32** [comment]
Tout fonctionne de mon coté, en actualisant le problème persiste?

**Comment by maelvls** [comment]
Je viens de réessayer depuis chez moi, et ça marche... Hmm... Je crois que le bug n'apparait que sur le réseau interne de l'institut de mathématiques :)

MàJ: ah bah non, ça marche pas non plus chez moi ^^

**Comment by Erim32** [comment]
Peut être un problème de navigateur, sous chrome je n'ai pas de problème.
Quel navigateur utilisez vous?

**Comment by maelvls** [comment]
Safari

**Comment by Erim32** [comment]
Je confirme le problème est que Safari ne prend pas en charge xmlhttprequest comme une fonction. [(doc)](http://caniuse.com/#search=xmlhttprequest) 
Je préparerais un fix ultérieurement.

**Comment by maelvls** [comment]
Problème réglé dans #3
